ERROR | 2023-02-02 15:20:09,556 | main.py:41 | Bot started
NoneType: None
